[Logger]
Debug = true
Level = "debug"
CallerSkip = 1

[Logger.File]
Enable = false
Path = "data/log/ginadmin.log"
MaxBackups = 20 # Files
MaxSize = 64 # MB

[[Logger.Hooks]]
Enable = true
Level = "info"
Type = "gorm" # gorm
MaxBuffer = 1024
MaxThread = 2

[Logger.Hooks.Options]
Debug = "false"
DBType = "sqlite3" # sqlite3/mysql/postgres
DSN = "data/ginadmin.db"
MaxOpenConns = "16"
MaxIdleConns = "4"
MaxLifetime = "86400"
MaxIdleTime = "7200"